### ISSUE TITLE
screenfull.js drop support for Bower

### ISSUE THREAD

**Issue by mladencosmic** [hrajchert/angular-screenfull#12]
You added dependency for screenfull.js 3.0.0 but they drop the support for bower
https://github.com/sindresorhus/screenfull.js/releases

**Comment by hrajchert** [comment]
You are right. Screenfull.js droped bower as it's becoming less suported by open source projects. It would be nice to either update the documentation or to provide a special bundle with both angular-screenfull and screenfull.js.

PR are more than welcome :D
