### ISSUE TITLE
FullScreen for Multiple Video Player

### ISSUE THREAD

**Issue by slimshadddyyy** [hrajchert/angular-screenfull#13]
Hi,
How do I use this plugin for multiple video players. For example the below code will work for single player or div that will be displayed fullscreen

```

<div ngsf-fullscreen="fullscreenCtrl">
Content Goes Here
<button ng-click="fullscreenCtrl.toggleFullscreen()"/>
</div>
```

 For multiple, I tried below code and passed uniq id but its not working and full screen is applied on last element. 

```
<div ngsf-fullscreen="fullscreenCtrl">
Content Goes Here
<button ng-click="fullscreenCtrl.toggleFullscreen('myUniqId')"/>
</div>
```

Please guide and help on how to make it work for multiple instances to be full screened.

Thanks !

**Comment by hrajchert** [comment]
Hi! the `ngsf-fullscreen` directive exposes its controller under the name given. In this particular  case you are exposing both controllers as fullscreenCtrl, which means that ones is going to overwrite the other one.

Also the method toggleFullscreen doesn't have a parameter.

You should do something like

```
<div ngsf-fullscreen="ctrl1">
First Content Goes Here
<button ng-click="ctrl1.toggleFullscreen()"/>
</div>

<div ngsf-fullscreen="ctrl2">
Second Content Goes Here
<button ng-click="ctrl2.toggleFullscreen()"/>
</div>
```
