### ISSUE TITLE
Screenfull 3.0.0 dependency

### ISSUE THREAD

**Issue by kingrollo** [hrajchert/angular-screenfull#14]
How are you guys working around the fact that Screenfull 3.0.0 isn't in Bower? The [release notes](https://github.com/sindresorhus/screenfull.js/releases/tag/v3.0.0) say "Drop support for Bower. Just use npm. Nothing new. Just stay with 2.0.0 if you need Bower support."

You had updated to 3.0.0 in 56fe23461710f0d9ccf247a00de67d9f2da4429e, but it sounds as though this might be unnecessary?

I'm working around this by using angular-screenful 0.1.1 and screenfull 2.0.0, but I'd be interested to hear the _right_ answer...

Thanks!

**Comment by hrajchert** [comment]
Hi @kingrollo! 

I'm afraind there isn't a _right_ answer, I use version 0.1.0 myself as I don't require the changes introduced in 0.1.1, and I created the library 😅.

As the community is droping support for bower I guess the correct approach would be to drop bower too and update the docs to use npm instead.

PR's are welcome if you want to contribute :)

Thank you for taking the time to comment!

**Comment by kingrollo** [comment]
Interesting, thanks - is there a summary of changes between 0.1.0 and 0.1.1 somewhere? Was it just the animation? If so, I might be able to downgrade as well.

I'm still using bower (this was the first time I'd noticed reduced support to be honest!) so my PR would probably just involve downgrading to 2.0.0 at this stage, and I'm guessing that wouldn't be a popular move...

**Comment by hrajchert** [comment]
Ups, sorry I missed this.

There is no new feature nor bug fix between 0.1.0 and 0.1.1 it was just the version upgrade and some documentation.

I'm still using bower to, but migrating away of, as angular and other major projects are doing, in favour of npm

**Comment by kingrollo** [comment]
No problem - thanks very much!

**Comment by kingrollo** [comment]
Hi again,

OK... I downgraded to angular-screenfull 0.1.0, and it looks as though fullscreen mode might have stopped working properly in Chrome - does that sound feasible?

It was filling the screen OK, but the Marzipano component I've got inside it lost all its functionality, and it worked again once I switched back to 0.1.1.

Thanks!

**Comment by hrajchert** [comment]
I've updated the version of the dependecy to 3.3.2, sorry about the delay, more details [here](https://github.com/hrajchert/angular-screenfull/issues/19#issuecomment-385779408)
