### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by Mr-Anonymous** [hrajchert/angular-screenfull#16]
Thank you for this awesome plugin. I love it and it took me 2 mins to set it up. I installed it in my Angular 1.5 with the current version of this plugin and Screenfull version 3.0.0 and it works perfectly so far. So just a quick drop-in to say thank you. Thats all.

Cheers,
Neel.

**Comment by hrajchert** [comment]
So much love ❤️. Thank you 😊
