### ISSUE TITLE
Not working in iPad

### ISSUE THREAD

**Issue by Mr-Anonymous** [hrajchert/angular-screenfull#18]
Hi,

I cant get this plugin to work in iPad. I tested it from mobiles, laptops and other touch screen notebooks where it works. But in iPad, nothing happens when the full screen button is clicked. I tried this from both Chrome as well as Safari (v9) in iPad. I have a fairly old iPad 2 and I was wondering if this is a known limitation of screenfull plugin or is it just because of my iPad 2 which is old? 

Thanks,
Neel.

**Comment by hrajchert** [comment]
Hi Neel, sorry for the late response, I was on my hollidays.

This library is a small wrapper to consume the https://github.com/sindresorhus/screenfull.js/ library in an "angular 1 way". If the `request` method doesn't work for a particular device we could report the bug there. 

In the following days I'll update this library to make sure it works properly on npm, drop bower altogether and update the screenfull dependency as well.

Cheers.

**Comment by Mr-Anonymous** [comment]
Fair enough. Thank you hrajchert. Hope you had a good holiday! Cheers.
