### ISSUE TITLE
just ask a coding style

### ISSUE THREAD

**Issue by microlv** [hrajchert/angular-screenfull#2]
Hello, I saw your code, could you tell me what reason you like to use the code like A not B?
It is something better??

``` js
A
NgsfFullscreenController.$inject = ['$scope', '$document', '$element', '$animate'];
function NgsfFullscreenController ($scope, $document, $elm, $animate) {
```

``` js
B
angular.controller('NgsfFullscreenController',['$scope', '$document', '$element', '$animate'
      function($scope, $document, $elm, $animate){

}]);
```

**Comment by hrajchert** [comment]
Hi! I follow john papas style guide. In this particular issue you can see why he chooses to use `$inject`

https://github.com/johnpapa/angular-styleguide#style-y091

One of my personal reasons to use this approach is that its more readable when you have lots of dependencies.

**Comment by microlv** [comment]
thanks. that's great!
