### ISSUE TITLE
Screen goes black after full screen

### ISSUE THREAD

**Issue by gauravlodha** [hrajchert/angular-screenfull#22]
Hi @hrajchert 

screen goes completely black after full screen can you help me on this and its happening on your demo also.

Thanks in advance.

![fullscreen](https://user-images.githubusercontent.com/26317446/49454404-15de0280-f80b-11e8-8727-ce839d4882e8.png)

**Comment by hrajchert** [comment]
hi @gauravlodha, thanks for letting me know, I have some busy days ahead but I'll look at it as soon as I can.

If you can figure it out and fix it, PR's are welcome. This is a simple wrapper around the Screenful library, which in turn is just a wrapper to the native API, as at the time of writing, each browser had small differences between them.

I would try using a simple example of the Screenful library in an "empty project", to see if there is a problem with your browser.

Also, it would help if you can give me which browser are you using and in what version is it on.

Thanks!

**Comment by gauravlodha** [comment]
@hrajchert, thanks for the quick reply

I have checked, the issue is in all major browser

Microsoft Edge 44.17763.1.0
IE 11
Mozzila 62
Chrome 70

and just today updated to chrome 71, now fullscreen toggling not working at all :(

![error](https://user-images.githubusercontent.com/26317446/49488456-bf091500-f86c-11e8-9d5f-59b32e9505ef.jpg)


hope you will get free time soon and it will get fixed, I will also try to resolve the issue.

**Comment by hrajchert** [comment]
Hi @gauravlodha! Sorry about the long time to respond. I updated the tooling so I could check out the examples once again and I noticed that the black screen is working as expected.

you can always change the background to be whatever you like, for example if you add 

```css
.fullscreen {
    background-color: red;
}
```

you can change the color to red. Probably you would like to add an element that its proper styled as the fullscreen element. My main use is a video player, which is the element that I "resize", so I don't have to use a background-color.

**Comment by hrajchert** [comment]
On the other part, the bug in chrome 70 was due to a bug in the dependency, I updated to 4.0.0 and the problem was fixed. You should update in your build system too.

Thanks for reporting :)
