### ISSUE TITLE
"requestFullscreen" doesn't work in Chrome 71

### ISSUE THREAD

**Issue by danielnemetz** [hrajchert/angular-screenfull#23]
Having a button with "ngsf-toggle-fullscreen" won't work anymore in Chrome 71 but did work in Chrome 70.

`Uncaught (in promise) TypeError: Failed to execute 'requestFullscreen' on 'Element': parameter 1 ('options') is not an object.`

Even Examples on project page are broken.

**Comment by hrajchert** [comment]
I upgraded screenful to 4.0.0, and angular-screenful to 1.0.0 to fix the problem. You should upgrade to 4.0.0 in your setup as well. 

Cheers!, thanks for reporting :)

**Comment by simonberger** [comment]
@hrajchert The 1.0.0 release tag is yet missing.

**Comment by hrajchert** [comment]
You are right... done it :)
