### ISSUE TITLE
Is it possible to select what ngsf-fullscreen id to be opened as fullscreen?

### ISSUE THREAD

**Issue by mackelito** [hrajchert/angular-screenfull#3]
I have several divs (containing images) and would like to, on click be able to set which div is to be viewed.

Is that possible?

**Comment by hrajchert** [comment]
Of course you can! 

Even though you can have one `ngsf-fullscreen` per image I advise you to have one parent div to be the fullscreen container and have some logic to show one image at a time, kind of like a carrousel.

If you have multiple  `ngsf-fullscreen`  containers, moving from image to image (for example using your left and right keys or swiping) would not be possible or would cause the fullscreen to close and reopen.

In any case, if you want to have multiple fullscreen containers you have 2 options to select which to open.

The easiest one would be to depend on the DOM hierarchy. If you have this code 

``` html
<div ngsf-fullscreen>
  <img src="img1.jpg" ngsf-toggle-fullscreen>
</div>
<div ngsf-fullscreen>
  <img src="img2.jpg" ngsf-toggle-fullscreen>
</div>
```

When you click on an image it will go fullscreen, you don't have to do anything else. Note that I have not tested this particular code but it should work. The directive `ngsf-toggle-fullscreen` requires to have a parent `ngsf-fullscreen`, and it will toggle its fullscreen status.

The other option would be to export each `ngsf-fullscreen` controller into the scope and then you can toggle fullscreen or do other things inside the controller. Something like

``` html
<div ng-repeat="image in images" >
  <img ng-src="image.src" ngsf-fullscreen="imageCtrls[$index]">
</div>
```

``` js
controller($scope) {
  // Toggle fullscreen status
  $scope.imageCtrls[2].toggleFullscreen();
  // Check if the element is fullscreen
  $scope.imageCtrls[2].isFullscreen();
  // Request the image to become fullscreen 
  $scope.imageCtrls[2].requestFullscreen();
  // Make the image not to be fullscreen
  $scope.imageCtrls[2].removeFullscreen();
}
```

For this case I still recommend you to have only one fullscreen element and show the desired image.

Hope it helps!

**Comment by mackelito** [comment]
Sorry for the late reply.. I ended up creating my own solution but keep up the good work! :)
