### ISSUE TITLE
Still allow mouse and keyboard control when fullscreen?

### ISSUE THREAD

**Issue by MadEddieFFS** [hrajchert/angular-screenfull#5]
Not sure if its me or Firefox but I am trying to make an element fullsceen (a SWF object) and allow the user to interact with the SWF presentation using the mouse and keyboard. Currently the first click returns to "Normal View". Therefore is it possible to limit the toggle of fullscreen to just the escape or F11 keys rather than mouse clicks?

**Comment by hrajchert** [comment]
I havent tried using a SWF object. Can you provide a JSFiddle or similar to check the problem?

**Comment by hrajchert** [comment]
Closing for now, if you provide more feedback I'll reopen
