### ISSUE TITLE
What is the use of `show-if-fullscreen-enabled`

### ISSUE THREAD

**Issue by ghost** [hrajchert/angular-screenfull#6]
Why do we need `show-if-fullscreen-enabled` directive here in the example, what does it do?

```
<div ngsf-fullscreen>
<p>This is yet another fullscreen element</p>
<a ngsf-toggle-fullscreen show-if-fullscreen-enabled>
    <i show-if-fullscreen=false>Icon for enter fullscreen</i>
    <i show-if-fullscreen=true>Icon for exit fullscreen</i>
</a>
```

</div>

**Comment by hrajchert** [comment]
Because not all browsers have fullscreen capabilities and thats a way to hide the button altogether

**Comment by ghost** [comment]
Thanks for that. It would be good if you put that as a note on readme. if another noob like me comes across.

**Comment by hrajchert** [comment]
No problem! Thanks for contributing :)
