### ISSUE TITLE
how to disable full screen notification 

### ISSUE THREAD

**Issue by gmchaturvedi1** [hrajchert/angular-screenfull#7]
how to disable full screen notification

**Comment by hrajchert** [comment]
Hi! What notification are you talking about? The one that says something like: "yourdomain has requested full screen, allow or cancel"? 

If so, that message is from the standard itself, and its a security measure that you cannot avoid

**Comment by hrajchert** [comment]
Im closing this for now, if you have further comments I'll reopen
