### ISSUE TITLE
Show or hide

### ISSUE THREAD

**Issue by filipSu** [hrajchert/angular-screenfull#9]
Hello,

when I use show-if-fullscreen directive, it only works as expected for the first time. Second time the icons don't change properly (or at all).
Here is my code:
`
<md-button ngsf-toggle-fullscreen show-if-fullscreen-enabled hide-xs class="md-icon-button">
<md-icon show-if-fullscreen=false md-svg-icon="fullscreen"></md-icon>
<md-icon show-if-fullscreen=true md-svg-icon="fullscreen_exit"></md-icon>
</md-button>
`

**Comment by hrajchert** [comment]
Can you create a plunkr with the code you are trying? Or tell me if mine works.

Here is the example I use, http://plnkr.co/edit/akbNXmHGvPqHydqXot1w?p=preview
In order for it to work you have to click on the "Launch the preview in a separated window" icon on the top right of the preview as the fullscreen doesn't work on iframes

**Comment by hrajchert** [comment]
Closed for now, if issue arises again reopen with the code you are trying
